# docker compose -f .\docker-compose.ui-test.yml up --abort-on-container-exit
services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_WEATHER_SERVER: http://ui_test:5000
    networks:
      - weather-network

  ui_test:
    build:
      context: ./ui_test
    environment:
      - FRONTEND_URL=http://frontend:80
    depends_on:
      - frontend
    networks:
      - weather-network


networks:
  weather-network:
    driver: bridge