ui_test:
  build:
    context: ./ui_test
    dockerfile: Dockerfile
  environment:
    - FRONTEND_URL=http://nginx:80
    - OW_API_KEY=${OW_API_KEY}
    - VC_API_KEY=${VC_API_KEY}
  depends_on:
    - nginx
    - backend
  networks:
    - weather-network-ui-test
  # Убираем command из docker-compose, так как он уже в Dockerfile