name: UI Tests with Selenide and Allure Report

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Start frontend server
      - name: Start Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm start > frontend.log 2>&1 &
          sleep 15
          curl --retry 5 --retry-delay 3 --retry-all-errors http://localhost:5173 || cat frontend.log

      # 3. Setup Java 17
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 4. Install Chrome and WebDriver
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      # 5. Run tests with optimized Selenide config
      - name: Run Tests
        working-directory: ./ui_test
        env:
          SELENIDE_BROWSER: "chrome"
          SELENIDE_TIMEOUT: "15000"
        run: |
          mvn clean test \
            -Dselenide.headless=true \
            -Dselenide.browser=$SELENIDE_BROWSER \
            -Dselenide.timeout=$SELENIDE_TIMEOUT \
            -Dselenide.pageLoadStrategy=normal \
            -Dchromeoptions.args='--disable-dev-shm-usage,--no-sandbox,--disable-gpu,--window-size=1366,768' \
            -Dwebdriver.chrome.whitelistedIps="" \
            -Dallure.results.directory=target/allure-results

      # 6. Save Allure results
      - name: Save Allure Results
        working-directory: ./ui_test
        run: |
          mkdir -p allure-results
          [ -d target/allure-results ] && cp -r target/allure-results/* allure-results/ || echo "No allure results found"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: ./ui_test/allure-results/
          retention-days: 3

      # 8. Cleanup
      - name: Stop Frontend
        run: |
          pkill -f "npm start" || true
          pkill -f "chrome" || true

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate Allure Report
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download allure results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: ./ui_test/target/allure-results

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate Allure Report
        working-directory: ./ui_test
        run: |
          mvn allure:report

      - name: Archive Allure Report
        run: |
          mkdir -p allure-report
          cp -r ./ui_test/target/allure-report/* public/
          
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./public
          retention-days: 7

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Publish Report to GitHub Pages
    steps:
      - name: Download Allure Report
        uses: actions/download-artifact@v3
        with:
          name: allure-report
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_path: ./public